### ISSUE TITLE
Page <title> should reflect the page the user is in

### ISSUE THREAD

**Issue by riggraz** [astuto/astuto#117]
Right now the site's title is always the site's name, as you can see from the `application.html.erb` file:

`<title><%= Rails.application.name %></title>`

It would be nice if the title changed with the page, e.g. when on board "Feature requests" it should be something like "Feature requests | App name", on a post "Post title | App name", and so on.

**Comment by pdthomson** [comment]
First time here and I would love to take this ticket on, if you could please assign it to me!

**Comment by riggraz** [comment]
There you go! If you need help or want to discuss something feel free to reach out 😉

**Comment by pdthomson** [comment]
Thank you! Ill get it pulled down and start right away! If I have any questions ill be sure to reach out!

**Comment by riggraz** [comment]
Hi @pdthomson ! Any updates on this?

**Comment by anderson-mj** [comment]
Was gonna take this but looks like it's been changed, right? I believe this issue should be closed.
`application.html.erb` now uses `<title><%= @tenant ? @tenant.site_name : @page_title %></title>`

**Comment by riggraz** [comment]
Actually I was thinking about the title being more dynamic, e.g. if on a post page it should be the post title, if on a board it should be the board name, etc

Ideally it should be: 'Page Name | Tenant Name'
For example: 'Awesome feature request | My Feedback Space'
