### ISSUE TITLE
Password confirmation field doesn't do anything on user signup

### ISSUE THREAD

**Issue by riggraz** [astuto/astuto#146]
A user can type anything on the "Password confirmation" field and, even though it's different to the provided password, the system will accept the submission and create a new user. It needs to be fixed in order to perform submission only if password and password confirmation are the same.

![Screenshot 2022-07-25 at 15 41 16](https://user-images.githubusercontent.com/31478034/180791789-8a37cf5e-451a-4f75-9ee5-6d769eb6cf8a.png)

**Comment by fakoredeDamilola** [comment]
Hello...can I work on fixing this. Thanks

**Comment by riggraz** [comment]
Hi Damilola!

Of course you can work on it! If you're new, I suggest reading the coding section of the [contribution guidelines](https://github.com/riggraz/astuto/blob/main/CONTRIBUTING.md#coding-and-testing).

Let me know if you need additional information, I'd be glad to help.

**Comment by fakoredeDamilola** [comment]
Thank you
