### ISSUE TITLE
Allow anonymus interaction

### ISSUE THREAD

**Issue by tautf** [astuto/astuto#170]
It would be great to allow anonymus interaction as comments and upvotes.

**Comment by riggraz** [comment]
This is definitely something that was on my mind and will be added in the future.

**To think**: how to avoid spam (captcha? something else?)

**Comment by Brugman** [comment]
If you go captcha make it Turnstile.

**Comment by riggraz** [comment]
Feature implemented! It's now possible to decide whether to accept anonymous feedback or not. You can also setup anonymous feedback to require approval from moderators or admins before it gets publicly displayed.

I decided to go lightweight with anti spam measures: no captcha, just honeypot fields and time checks to detect most spambots. If they prove to be ineffective, we'll think about adding captcha, but for now I think it's enough :)
