### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by K1LLUM1N471** [astuto/astuto#208]
Hello,
I miss some basic features like a rich text editor and the ability to upload images/screenshots.
Are these features hidden somewhere or will they at least be implemented sometime in the near future?
Kind regards,
K1LLUM1N471

**Comment by riggraz** [comment]
Hi!

Right now you can type markdown in textboxes and the text will be rendered accordingly. Right now there is no plan on adding richer editors more powerful than markdown.

Image upload is something that will be added in the future, but I don't know when. If you'd like to help with that let me know!
