### ISSUE TITLE
A Post Status can't be deleted if there are Posts with that status

### ISSUE THREAD

**Issue by riggraz** [astuto/astuto#219]
Due to SQL constraints, a PostStatus may be referenced by a Post and/or a PostStatusChange. If that's the case, right now the PostStatus cannot be deleted.

It should be possible to delete a PostStatus even though it's linked to a Post. For example, the PostStatus reference on the Post should become null. On the other hand, maybe PostStatusChange should be deleted.

**Comment by PapePathe** [comment]
Seems like this issue is fixed. I tried to reproduce it quickly on a github codespace but the test does not fail. Are we planning to close this one so that future contributors do not spend time trying to solve this issue ?
