### ISSUE TITLE
Copy Pasting Images/Screenshots

### ISSUE THREAD

**Issue by Jelias95** [astuto/astuto#232]
We're attempting to copy and paste a screenshot as part of a post or comment and the paste does not work. It would be helpful to support this feature for users to provide additional details like code snippets or sections of a log output without ruining the formatting

**Comment by riggraz** [comment]
Hi Jelias, thanks for reaching out.

That would indeed be an interesting feature. Also related to an issue I just opened (#253) about uploading images.

**Comment by riggraz** [comment]
Your suggestion has been added to issue #253, so I'm closing this now. Thanks again for your suggestion!
