### ISSUE TITLE
site_logo value that doens't point to a file/url causes unrecoverable crash

### ISSUE THREAD

**Issue by MonoDepth** [astuto/astuto#238]
If you save any value as the Site Logo that doesn't point to an actual image on disk or url to an image the whole frontend UI will enter an error state which can only be resolved by changing the public.tenants site_logo value in the database manually.

The call to `image_tag` in `app/views/layouts/_header.html.erb` throws an exception
```
Sprockets::Rails::Helper::AssetNotFound in StaticPages#root 
Showing /astuto/app/views/layouts/_header.html.erb where line #6 raised:

The asset "a" is not present in the asset pipeline.
```

This could be solved by adding the `skip_pipeline: true` to the image_tag call which would instead result in a broken image link in the UI
I can submit a PR if this is an acceptable solution but I'm not familiar with the ruby ecosystem so there might be a better solution 🙂 

Steps to reproduce
* Go to Site Settings
* Input non url value in the Site Logo input field eg. "a"
* Press save
* Site wide error message
![error_message](https://github.com/astuto/astuto/assets/11025533/668b6c6c-0568-4b6f-9628-5fec4a7f1e8a)

**Comment by riggraz** [comment]
Hi MonoDepth, thanks for pointing that out and sorry for my late response. I think your solution is great, if you want to open a PR for it you're more than welcome!
