### ISSUE TITLE
(Maybe) wrong Content Type for Discord's OAuth

### ISSUE THREAD

**Issue by Giggiux** [astuto/astuto#273]
According to [Discord's Documentation](https://discord.com/developers/docs/topics/oauth2#shared-resources) the correct content type for the Token's request is `application/x-www-form-urlencoded`. This means that the token request in astuto is rejected by Discord and automatically all the test/login attempts fail with a 401 Unauthorized, due to not having the token.

Quoting the relevant part from discord:

> In accordance with the relevant RFCs, the token and token revocation URLs will only accept a content type of `application/x-www-form-urlencoded`. JSON content is not permitted and will return an error.

I not expert in Ruby, so I am definitely not sure about this, but maybe the `HTTParty` is sending a the content as `application/json`? But again, not 100% sure.
 
https://github.com/astuto/astuto/blob/9c5553cc320142507f12b220e82a32ce525718e2/app/workflows/o_auth_exchange_auth_code_for_profile_workflow.rb#L36-L40

Hopefully you can help me solve the issue!
Grazie!

**Comment by riggraz** [comment]
Hi Giggiux!

I think the `Accept` header is used to instruct the OAuth server to return content in `application/json`, but that doesn't mean that we're sending json.

Anyway, have you tried to set up Discord as an oauth provider? Because we have [official documentation](https://docs.astuto.io/oauth/common-oauth-providers#discord) for it (I know it's not linked anywhere, I'll fix this soon 😅) and the last time I tried to configure it it worked fine. Let me know

**Comment by riggraz** [comment]
That's strange.. can you provide more information, for example Rails logs if they're available? Thank you!

**Comment by Giggiux** [comment]
Sorry for the long wait: the docker container has 0 logs related to the error. This is most probably due to the logger statement being disabled in the "production" environment... I guess?

How can I enable them for debugging purposes?

**Comment by riggraz** [comment]
Try to add to your `docker-compose.yml`, in the web service, the environment variable `RAILS_LOG_TO_STDOUT` set to true. This should log everything to stdout!

**Comment by brink668** [comment]
Having the same issue with Docker. 

Discord OAuth test results
Fetched user data
{
  "message": "401: Unauthorized",
  "code": 0
}
Email ❌
Json User Email Path: email
Found:
Full name ⚠️
Json User Name Path: username
Found:
Summary ❌
This OAuth provider is NOT configured correctly.

**Comment by riggraz** [comment]
Thank you @brink668 , I'll add the identify scope to the documentation!

**Comment by riggraz** [comment]
I think Discord login is working now, so I'm closing this issue. If you encounter any problems, feel free to reopen the issue! Thanks
