### ISSUE TITLE
Send emails to admins/mods on new feedback published

### ISSUE THREAD

**Issue by riggraz** [astuto/astuto#319]
A recap email should contain the new feedbacks published or the in the moderation queue.

Doubts:
- Always send an email when a new feedback is received? Or, better, there should also be a setting, under "Profile settings", to let owner/admins/mods decide whether or not to receive recap emails ("Never", "Every day", "Every week", "Every month")?
- Email notifications for posted feedback should have the same behaviour and settings as the feedback that is posted but awaits in the moderation queue?

**Comment by stephanemagnenat** [comment]
Personally, as a customer of astuto for my product https://cand.li, I would consider moderation requests possibly more important, because before a content is moderated, the user who posted it does not see anything posted, and so is not ideal. That means I would prioritize accepting feedback, before sorting them, giving answers, and other tasks.

**Comment by riggraz** [comment]
Hi @stephanemagnenat, sorry for the late reply but I was very busy working on another Astuto feature (the API).

I understand that feedback pending approval in the moderation queue should have more priority, however I am a bit reluctant  in sending an email for each new posted feedback or for each new feedback pending approval. This may result in a lot of emails sent if a lot of feedback is coming in.

A simple solution I came up with is the following: send a daily recap email containing the number of new feedback posted + the number of feedback awaiting approval. The email will not be sent if there are no new feedbacks.

I know that with this approach the notification is not immediate, however in the worst case a feedback will only wait 24 hours before getting your attention. Do you think this solution may work for you?

Let me know :)

**Comment by stephanemagnenat** [comment]
I think that a daily recap email if needed is a good tradeoff!

**Comment by riggraz** [comment]
Happy to hear that! I'll be working on it in the coming weeks and I'll let you know when the feature has been implemented!

**Comment by riggraz** [comment]
Just wanted to let you know that there is a bug on recap emails, so right now they are not sent. The fact is that I changed the way mails are sent under the hood so I need a little bit more time to make sure everything works as expected.

I'm sorry for the inconvenience and I'll get back to you as soon as the problem is fixed!

**Comment by stephanemagnenat** [comment]
No problem, this can happen!

Note that I'm seeing this message when logged in:
`You have to [enable Sidekiq](https://docs.astuto.io/deploy-with-sidekiq) to receive recap notifications.`

I assume that this will go away once the configuration is completed on your side.

**Comment by riggraz** [comment]
Yes, anyway thanks for pointing that out! That message should only be shown to people self-hosting Astuto.

I fixed it and I should also have fixed the recap email, starting from tomorrow it should arrive at 15:00 (only if there is new feedback, as I stated in a few comments above).

**Comment by riggraz** [comment]
Hi @stephanemagnenat, everything should work as expected now! Anyway let me know if you encounter any further issues :)

**Comment by stephanemagnenat** [comment]
An absolute detail: when I accept or reject a feedback, the counter on top of my name on the top-right of the page is not updated. That is not a big issue at all.

**Comment by riggraz** [comment]
I knew that.. it may sound strange, but for technical reasons making that number update in real time on approving/rejecting feedback takes too much effort that it's not worth it right now 😅 anyway I'll open an issue so I don't forget about it!

**Comment by stephanemagnenat** [comment]
Yes, I fully understand, just wanted to let you know!
