### ISSUE TITLE
Self hosted: Subscription expired. Renew it to continue using.

### ISSUE THREAD

**Issue by pilasguru** [astuto/astuto#356]
Do the self hosted (docker) version requires a subscription? 

When anybody submit a new feedback a red message is displayed:

```
Your subscription has expired. Please renew it to continue using the service.
```

I have just restarted astuto app with latest image available and the message remains there:

```
riggraz/astuto       latest      4abc2c0663ff   4 days ago      582MB
```

**Comment by riggraz** [comment]
Hi pilasguru,

no, the self-hosted version is free and will be free forever.

How long have you been running Astuto? I think I know what is the problem: probably the update to Astuto that added the paid plain option have internally started a trial period also for self-hosted version.

This is a bug and I'll fix it today. Sorry for the inconvenience!

**Comment by riggraz** [comment]
@pilasguru I pushed an hotfix that should solve the issue. Please pull the latest Docker image and let me know if it works for you :)
