### ISSUE TITLE
Add filter by board to Roadmap

### ISSUE THREAD

**Issue by Brugman** [astuto/astuto#360]
Hiya. This may be impossible with the current data structure, but I'd like a separate roadmap for each board. In my use-case, each board is for a product. The roadmap page is a nice feature, but if it shows 100 cards for 10 different products all mixed up - then I'd rather not use it. Most customers will only use 1 or 2 products, and I don't want to bother them with cards discussing the other 8.

**Comment by Brugman** [comment]
Great idea!

**Comment by riggraz** [comment]
Okay, I updated the title of the issue :)
