### ISSUE TITLE
SMTP configuration not working

### ISSUE THREAD

**Issue by tgrignon** [astuto/astuto#364]
I tried to use your software and it seems to be what I need, but the SMTP not working.

I have a local relay with a local IP without any authentication, but not working. I tried without user/pass environment, but docker not start if I don't use it.

      EMAIL_DELIVERY_METHOD: "smtp"
      EMAIL_SMTP_HOST: "192.168.1.2"
      EMAIL_SMTP_USER: ""
      EMAIL_SMTP_PASS: ""
      EMAIL_SMTP_AUTH: false
      EMAIL_SMTP_STARTTLS_AUTO: false

**Comment by pilasguru** [comment]
Refer to #317 #330

**Comment by riggraz** [comment]
Moving this conversation to #330
