### ISSUE TITLE
Avoid dropdown menu closing on click inside

### ISSUE THREAD

**Issue by riggraz** [astuto/astuto#374]
Bootstrap's dropdown should close if I click outside of it or on a dropdown button, but not if I click on empty space inside the dropdown.

See: https://stackoverflow.com/questions/25089297/avoid-dropdown-menu-close-on-click-inside

**Comment by rishabhj1717** [comment]
@riggraz I'd like to take this issue up?

**Comment by riggraz** [comment]
@rishabhj1717 yes, of course!
