### ISSUE TITLE
Redirect to previous page after logging in

### ISSUE THREAD

**Issue by riggraz** [astuto/astuto#377]
Right now, after a successful log in users are redirected to the root page. However, a user may decide to log in (or sign up) clicking the "log in" button in the board page or in the comments section. After successful log in, those users should be redirected back to the page they were visiting.

**Comment by askadityapandey** [comment]
Can I work on this one? @riggraz 
The project seems cool to me!

**Comment by riggraz** [comment]
Hi @askadityapandey, yes of course I assign this task to you!

Thank you very much for your contribution!
