### ISSUE TITLE
Problem when installing Astuto via docker

### ISSUE THREAD

**Issue by Mlou5ia** [astuto/astuto#95]
Hello
I installed Astuto via docker-compose:
![ast1](https://user-images.githubusercontent.com/63925881/159453504-49db5cb5-6e65-4bdc-902b-a84e7a71848c.PNG)

but when i try to access the website, it show me this:
![ast2](https://user-images.githubusercontent.com/63925881/159453674-1fe68858-124b-4eaf-b9bf-c3069d7b16fb.PNG)

and in the the console i got this error message:
![ast3](https://user-images.githubusercontent.com/63925881/159453872-0cedbaff-f16e-48bb-b6d0-84156cbc68f9.PNG)

Here are the logs:
![ast4](https://user-images.githubusercontent.com/63925881/159454618-b2d37d3f-71ec-4389-b33d-90e4aaf79cc4.PNG)
![ast5](https://user-images.githubusercontent.com/63925881/159454636-6dc7cfaa-b393-4322-af17-ab1a24799f71.PNG)

Can you help please ?
Thanks

**Comment by greenlighttec** [comment]
Same  issue log file contains

`db_1   | 2022-06-17 12:54:17.912 UTC [71] ERROR:  relation "boards" does not exist at character 454
db_1   | 2022-06-17 12:54:17.912 UTC [71] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
db_1   |               pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
db_1   |               c.collname, col_description(a.attrelid, a.attnum) AS comment
db_1   |          FROM pg_attribute a
db_1   |          LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
db_1   |          LEFT JOIN pg_type t ON a.atttypid = t.oid
db_1   |          LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
db_1   |         WHERE a.attrelid = '"boards"'::regclass
db_1   |           AND a.attnum > 0 AND NOT a.attisdropped
db_1   |         ORDER BY a.attnum
db_1   |
`

**Comment by riggraz** [comment]
Hi guys 👋🏻 we just went through some major changes in Docker configuration so I think this problem could be fixed!

Please, try to follow the new instructions in README to install Astuto from the DockerHub image, and let me know if it works for you.

**Comment by riggraz** [comment]
Closing this issue because a lot has changed since last year and no updates on the issue have been provided!
